name: design_tokens
description: Package containing design token files
version: 0.7.0

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  args: ^2.4.2
  flutter_lints: ^4.0.0
